name: CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports: ["6379:6379"]
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build and run test
        env:
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          # Adjust your setup steps accordingly based on your project requirements
          bundle exec rake db:create
          bundle exec rake db:migrate
